### ISSUE TITLE
[API] Request Issuing VC：/api/issuer/issuance-request-callback

### ISSUE THREAD

**Issue by hanchenglin** [58web3/re-action#22]
Reference source:
https://github.com/Azure-Samples/active-directory-verifiable-credentials-node/blob/main/1-node-api-idtokenhint/issuer.js

- /api/issuer/issuance-request-callback

参考記事：
Microsoft Entra Verified ID の動きをみてみた。発行編： https://zenn.dev/nerocrux/articles/ee34b2c18c5752
Backgroud(Authenticator)　SDK:
https://github.com/microsoft/entra-verifiedid-wallet-library-android/blob/daf9fd6450456408e9d590a7b1dc8bcd5ef416bc/walletlibrary/src/main/java/com/microsoft/walletlibrary/did/sdk/IssuanceService.kt

**Comment by maihao1997** [comment]
@hanchenglin 
Hi, can you confirm VC related issues. https://github.com/58web3/re-action/issues/22 https://github.com/58web3/re-action/issues/23 https://github.com/58web3/re-action/issues/24 https://github.com/58web3/re-action/issues/25 https://github.com/58web3/re-action/issues/26 https://github.com/58web3/re-action/issues/27 https://github.com/58web3/re-action/issues/28
I apologize for not creating a PR for each issue but grouping them into a PR that is https://github.com/58web3/re-action/pull/43.
Because they are related, separating each PR is difficult to test.

**Comment by hanchenglin** [comment]
> @hanchenglin Hi, can you confirm VC related issues. #22 #23 #24 #25 #26 #27 #28 I apologize for not creating a PR for each issue but grouping them into a PR that is #43. Because they are related, separating each PR is difficult to test.

@maihao1997 Thank you very much!
I am checking Issuance repsonse API.

**Comment by maihao1997** [comment]
@hanchenglin Thank you!

**Comment by hanchenglin** [comment]
@maihao1997 Hi!
I am trying to  issue VC without Authenticator.
I changed requestDID method of frontend/src/components/IssueVc/ModalIssueVC.vue in branch feature/api_#23.
I want to run  /v1.0/tenants/766072a8-e18b-4139-b3f4-4bbc875ff40b/verifiableCredentials/completeIssuance to issue card in Backend.

But there is an badrequest error.
Can you check api/src/services/issuer.js code.

Maybe can see Android SDK code https://github.com/microsoft/entra-verifiedid-wallet-library-android/blob/dev/walletlibrary/src/main/java/com/microsoft/walletlibrary/did/sdk/datasource/network/apis/IssuanceApis.kt

**Comment by maihao1997** [comment]
@hanchenglin  Hi! I also got the same error as you and I still haven't solved it. If you find related documents about it please share with me.

**Comment by hanchenglin** [comment]
close
